FastStore.Web/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace FastStore.Web.Models
{
    public class LoginViewModel
    {
        [Display(Name ="Usuário")]
        public string Login { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name ="Senha")]
        public string Senha { get; set; }
        [Display(Name ="Lembrar-Me?")]
        public bool LembrarMe { get; set; }
    }
}

FastStore.Web/Controllers/ArquivoController.cs
using FastStore.Domain.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FastStore.Web.Controllers
{
    public class ArquivoController : Controller
    {
        // GET: Arquivo
        public ActionResult ExibirImagem(int id)
        {
            using (ProdutoContexto db = new ProdutoContexto())
            {
                var arquivoRetorno = db.Produtos.Find(id);
                return File(arquivoRetorno.Imagem, arquivoRetorno.ImagemTipo);
            }
           
        }
    }
}

FastStore.Web/Controllers/NavegaController.cs
using FastStore.Domain.Entidades;
using FastStore.Domain.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FastStore.Web.Controllers
{
    public class NavegaController : Controller
    {
        private IRepositorio<Categoria> _RepositorioCategoria;
        public NavegaController()
        {
            _RepositorioCategoria = new CategoriaRepositorio(new ProdutoContexto());
        }

        public ActionResult Menu()
        {
            var categorias = _RepositorioCategoria.GetTodos();
            return PartialView(categorias);
        }
    }
}

FastStore.Web/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;
using FastStore.Domain.Entidades;
using FastStore.Web.Models;

namespace FastStore.Web.Controllers
{
    public class UsuarioController : Controller
    {
        private ProdutoContexto db = new ProdutoContexto();

        public ActionResult Login(string ReturnUrl)
        {
            ViewBag.ReturnUrl = ReturnUrl;
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel model, string ReturnUrl)
        {
            //validar login do usuario
            if (!ModelState.IsValid)
            {
                return View();
            }

            using(ProdutoContexto dc = new ProdutoContexto())
            {
                var _usuario = dc.Usuarios.Where(u => u.Login.Equals(model.Login)).FirstOrDefault();
                if (!Crypto.VerifyHashedPassword(_usuario.Senha, model.Senha))
                {
                    _usuario = null;
                }
                if (_usuario != null)
                {
                    FormsAuthentication.SetAuthCookie(_usuario.Login, model.LembrarMe);
                    if (Url.IsLocalUrl(ReturnUrl))
                    {
                        return Redirect(ReturnUrl);
                    }
                    else
                    {
                        return RedirectToAction("MenuAdmin", "Admin");
                    }
                }
            }
            ModelState.Remove("Senha");
            ModelState.AddModelError("", "Login Inválido");
            return View(model);
        }

        //logout
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Catalogo", "Produto");
        }

        //Registro do usuario

        public ActionResult Registro()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Registro(RegistroViewModel model)
        {
            if (ModelState.IsValid)
            {
                using(ProdutoContexto dc = new ProdutoContexto())
                {
                    var novoUsuario = new Usuario();
                    novoUsuario.Login = model.Nome;
                    novoUsuario.Senha = Crypto.HashPassword(novoUsuario.Senha);

                    dc.Usuarios.Add(novoUsuario);
                    dc.SaveChanges();
                    TempData["mensagem"] = string.Format("{0} : foi incluído com sucesso!", model.Nome);
                }
            }
            return View(model);
        }
        // GET: Usuario
        public ActionResult Index()
        {
            return View(db.Usuarios.ToList());
        }

        // GET: Usuario/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // GET: Usuario/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Usuario/Create
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Usuarioid,Login,Senha")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                //criptografar senha com hash
                usuario.Senha = Crypto.HashPassword(usuario.Senha);
                db.Usuarios.Add(usuario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(usuario);
        }

        // GET: Usuario/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: Usuario/Edit/5
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Usuarioid,Login,Senha")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usuario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(usuario);
        }

        // GET: Usuario/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: Usuario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Usuario usuario = db.Usuarios.Find(id);
            db.Usuarios.Remove(usuario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FastStore.Web/Views/Shared/_CatalogoResumo.cshtml
@model FastStore.Domain.Entidades.Produto

@{
    ViewBag.Title = "_CatalogoResumo";
}

<div class="well">
    <!--Verificando se produto tem imagem, se não tiver, usa a padrão-->
    @if (Model.Imagem != null)
    {
        <div class="pull-left" style="margin-right: 10px">
            <img class="img-thumbnail" src="@Url.Action("ExibirImagem", "Arquivo", new { id = Model.ProdutoId })" width="75" height="75"/>
        </div>
    }else
    {
        <div class="pull-left" style="margin-right: 10px">
            <img class="img-thumbnail" src="~/Imagens/semimagem.jpg" width="75" height="75"/>
        </div>        
    }

    <h3>
        <strong>@Model.Nome </strong>
        <span class="pull-right label label-primary">
            @Model.Preco.ToString("c")
        </span>
    </h3>

    @using (Html.BeginForm("AdicionarItemAoCarrinho", "Carrinho"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ProdutoId)
            @Html.Hidden("ReturnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Comprar" />
        </div>
    }
    <span class="lead">@Model.Descricao</span>
</div>

FastStore.Web/Views/Shared/_Error.cshtml
@{
    ViewBag.Title = "_Error";
}

<h1>Erro</h1>
<h4 class="text-danger">@Model.Exception.Message</h4>

FastStore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <title>@ViewBag.Title - FastStore</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">FASTSTORE</a>@Html.Partial("_Login")
        @Html.Action("ResumoCarrinho", "Carrinho")
    </div>
    <div class="row panel">
        <div id="categorias" class="col-xs-3">
            @Html.Action("Menu", "Navega")
        </div>
        <div class="col-xs-8">
            @if (TempData["Mensagem"] != null)
            {
                <div class="alert-success">@TempData["Mensagem"]</div>
            }
            @RenderBody()
        </div>
    </div>
</body></html>

FastStore.Web/Views/Shared/_Login.cshtml
@{
    if (Request.IsAuthenticated)
    {
        using (Html.BeginForm("Logout", "Usuario", FormMethod.Post, new { id = "logoutForm", @class = "nav navbar-nav navbar-form" }))
        {
            <h3>
                Bem-Vindo @(Request.IsAuthenticated ? HttpContext.Current.User.Identity.Name : "")
            </h3>
            <a href="javascript:document.getElementById('logoutForm').submit()">LOGOUT</a>
        }
    }
    else
    {
        <ul class="nav navbar-nav navbar-form">
            @Html.ActionLink("LOGIN", "Login", "Usuario")
        </ul>
    }
}